const helpData = {
    punkte: "<h3>Verteilte Punkte</h3><p>Das ist dein <b>Punkte-Budget</b> für den Charakterbogen: Jeder Punkt, den du in eine Fertigkeit unter <i>Handeln</i>, <i>Wissen</i> oder <i>Soziales</i> investierst, zählt hier mit. <b>Verteilte Punkte</b> ist die Summe davon, die Zahl rechts daneben (Standard <i>400</i>) dein Maximum.</p><p>Läufst du über dein Maximum, färbt sich die Anzeige rot - das ist keine Fehlermeldung, nur ein Hinweis, dass du mit deinem Spielleiter absprechen solltest, ob das so okay ist.</p><p>Ist gerade ein Hausregel-Paket (z.B. Eldara) mit eigener Kostenstaffel aktiv, wird das Maximum automatisch vom Paket vorgegeben und lässt sich nicht mehr von Hand ändern.</p>",

    hp: "<h3>Lebenspunkte</h3><p>Die große Zahl links ist dein <b>aktueller</b> HP-Wert, rechts vom Schrägstrich dein <b>Maximum</b>. Mit den kleinen <b>-</b>/<b>+</b>-Knöpfen direkt neben dem Maximum änderst du dein Maximum selbst (z.B. nach einem Levelaufstieg) - das ist nicht dasselbe wie Schaden nehmen!</p><p>Für Schaden und Heilung im Spiel nimmst du stattdessen die großen Knöpfe darunter (<b>-10/-5/-1/+1/+5/+10</b>) - die ändern nur den aktuellen Wert, dein Maximum bleibt unangetastet. Du kannst den aktuellen Wert auch direkt reinklicken und eine beliebige Zahl eintippen.</p>",

    skills: "<h3>1-Klick Würfeln</h3><p>Du kannst jederzeit direkt auf deine <b>Basiswerte</b> (Handeln, Wissen, Soziales) oder auf einzelne <b>Skills</b> klicken, um eine automatische Probe auf diesen Wert abzulegen!</p><p>Bei <b>Skills</b> werden kritische Erfolge (die unteren 10%) und Patzer (die oberen 10%) automatisch anhand deines aktuellen Wertes mitberechnet. Auf <b>Basiswerte</b> sind laut Regelwerk keine kritischen Erfolge möglich, Patzer können hier aber weiterhin auftreten.</p>",
    
    logs: "<h3>Drag & Drop Notizen</h3><p>Du kannst jeden Eintrag aus deinem <b>Aktions-Logbuch</b> oder den <b>Letzten Würfen</b> einfach mit der Maus greifen (klicken & gedrückt halten) und direkt rüber in dein <b>Notizfeld</b> ziehen!</p><p>So kannst du besondere Ereignisse oder knappe Würfe blitzschnell dokumentieren und musst sie nicht abtippen.</p>",
    
    gbp: "<h3>Geistesblitzpunkte (GBP)</h3><p>Geistesblitze sind seltene Meta-Punkte, die dir der Spielleiter für besonders kreatives Spielen oder gute Ideen geben kann. Du kannst sie jederzeit ausgeben, um die Story zu deinen Gunsten zu verändern (z.B. einen verpatzten Wurf doch noch zu schaffen oder einen versteckten Hinweis zu bekommen).</p>",
    
    inventory: "<h3>Sortieren & Löschen</h3><p>Du kannst deine Items und Waffen ganz einfach per <b>Drag & Drop</b> sortieren! Klicke auf das kleine Anfasser-Symbol (<i class='fa-solid fa-bars'></i>) auf der linken Seite eines Items, halte die Maus gedrückt und ziehe es an die gewünschte Position.</p>",
    
    dice: "<h3>Bonus & Custom Würfel</h3><p><b>Bonus/Malus:</b> Hat dir der Spielleiter einen situativen Bonus (z.B. +10) oder Malus (z.B. -15) gegeben? Trage ihn hier ein! Der Wert wird automatisch in deinen <i>nächsten</i> Skill-Wurf eingerechnet und danach direkt wieder zurückgesetzt.</p><p><b>Custom:</b> Hier kannst du unübliche Würfelkombinationen werfen, z.B. <code>3w8</code> für drei achtseitige Würfel.</p>",
    
    gehoertZu: "<h3>Gehört zu</h3>" +
               "<p>Optionales Feld für <b>Söldner/Mietlinge, die ein Spieler zusätzlich zu seinem eigenen Charakter führt</b> - vollwertiger Charakterbogen mit eigenem Talentbaum und Rasterinventar, aber in einer zweiten Browser-Verbindung (zweiter Tab, einmal \"Beitreten\" mit demselben Raumcode).</p>" +
               "<p>Trägst du hier z.B. \"Söldner von Tai Ming\" ein, erscheint das beim Spielleiter im GM-Dashboard als eigenes kleines Abzeichen über dem Charakter - so sieht er auf einen Blick, wer zu wem gehört, statt zwischen gleich aussehenden \"Spielern\" raten zu müssen. Rein informativ, hat keine Auswirkung auf Werte oder Regeln.</p>" +
               "<p><i>Leer lassen für einen normalen eigenständigen Charakter.</i></p>",

    status: "<h3>Status-Effekte</h3><p>Hier kannst du dir temporäre Effekte wie <i>Krankheit</i>, <i>Vergiftet</i> oder <i>Rausch</i> notieren. Du kannst ihnen einen Wert geben (z.B. <i>1W6</i> oder <i>-10</i>) und sie farblich markieren (Rot = Malus, Grün = Bonus).</p><p><b>Wirkt auf:</b> Trägst du beim Anlegen eine <b>ganze Zahl</b> als Wert ein UND wählst dabei eine Fertigkeit unter <i>Wirkt auf</i>, rechnet sich der Status automatisch als Bonus/Malus in jeden Wurf auf genau diese Fertigkeit ein - im Würfel-Logbuch siehst du dann, welcher Status mit eingerechnet wurde. Ohne Auswahl (Standard) bleibt der Status wie bisher reine Anzeige, die du selbst im Kopf behältst.</p><p>Klicke auf das Kreuz an einem bestehenden Status-Tag, um ihn wieder zu löschen.</p>",
    aktuelleWerte: "<h3>Aktuelle Werte</h3><p>Eine freie Tag-Liste direkt unter den Fertigkeiten - für alles, was sich gerade durch Ausrüstung, Zauber oder Effekte ändert und du griffbereit haben willst: Waffenschaden, Bewegung, Rüstung, ein Fertigkeitsbonus, eine Attributwert-Änderung, was auch immer. Kein festes Schema, genau wie bei den Status-Effekten - du trägst Bezeichnung und Wert einmal ein und passt bei Bedarf einfach die Zahl im Tag an (anklicken).</p><p>Anders als \"Wirkt auf\" bei den Status-Effekten rechnet sich hier <b>nichts automatisch</b> in Würfe ein - das ist bewusst eine reine Gedächtnisstütze, die du selbst pflegst und im Blick behältst.</p><p>Klicke auf das Kreuz an einem bestehenden Tag, um ihn wieder zu löschen.</p>",
    
    gmLayout: "<h3>Panels umsortieren</h3><p>Jedes Panel in der Hauptspalte (Spielerkarten, Zufallsgenerator, NSC-Liste, Quest-Logbuch, Schiff, Seekampf, Tischmitte, SL-Notizen) hat oben einen kleinen Ziehgriff <i class='fa-solid fa-grip-lines'></i>. Daran gepackt, kannst du das Panel per Drag &amp; Drop an eine beliebige Position ziehen - egal ob gerade Hausregeln aktiv sind oder nicht.</p><p>Die Reihenfolge bleibt in diesem Browser gespeichert, auch über einen Reload hinweg. Über <b>Reihenfolge zurücksetzen</b> geht's zurück zur Standard-Anordnung.</p>",

    gmSitzung: "<h3>SL-Sitzung sichern/laden</h3>" +
               "<p>Alles, was du als Spielleiter aufbaust - Karten (inkl. eigener Feldgröße je Karte), Seekampf, Kampf-Tracker, NSC-Liste, Tischmitte, Schiffs-Inventar und Quest-Log - speichert sich automatisch in diesem Browser. Ihr könnt also jederzeit an einem anderen Abend nahtlos weiterspielen, solange du denselben Browser auf demselben Gerät nutzt - dafür musst du nichts klicken.</p>" +
               "<p><b>Sichern</b> lädt trotzdem eine Datei herunter, die genau diesen Stand einfriert - praktisch als Backup vor größeren Änderungen, oder um auf einem anderen Gerät/Browser weiterzumachen.</p>" +
               "<p><b>Laden</b> ersetzt die aktuellen SL-Daten in diesem Browser komplett durch den Inhalt der Datei (mit Rückfrage) und lädt die Seite danach neu.</p>" +
               "<p><i>Das ist nicht dasselbe wie \"Speichern (JSON)\" oben - das sichert nur den Charakterbogen eines einzelnen Spielers. Für Spieler-Notizen gibt es außerdem ein eigenes Archiv (Notizen-Bereich).</i></p>",
    
    gmNotes: "<h3>Notizen-Archiv & Save/Load</h3><p>Das Dashboard speichert zu jedem verbundenen Charakter automatisch ein eigenes, für die Spieler geheimes Notizfeld in deinem Browser.</p><p>Klicke auf <b>Notizen-Archiv</b>, um auch die Notizen von Spielern einzusehen, die gerade offline sind.</p><p>Da die Notizen lokal im Browser liegen, solltest du sie nach jeder Session mit <b>Save</b> als Backup herunterladen und vor der nächsten Session mit <b>Load</b> wiederherstellen!</p>",
    
    multiplayer: "<h3>Live-Sync & Discord</h3><p><b><i class='fa-solid fa-satellite-dish'></i> Live-Sync (Multiplayer):</b> Dies ist das GM-Dashboard Feature! Ein Spieler oder der Spielleiter klickt auf diesen Button, um einen Server-Code zu generieren. Die anderen Spieler geben diesen Code ein und verbinden sich live (Peer-to-Peer, ohne echten Server). Der Host sieht alle Spieler-Bögen, HP und Würfe in Echtzeit!</p><p><b><i class='fa-brands fa-discord'></i> Discord Sync:</b> Du kannst hier eine Discord-Webhook-URL eintragen. Dann werden alle deine Würfe (und auf Wunsch auch HP-Verluste) vollautomatisch direkt in euren Discord-Kanal gepostet, sodass alle sie lesen können.</p>",
    
    gmDice: "<h3>GM Würfel-Box</h3><p><b>Schnelle Würfe:</b> Als Spielleiter hast du hier direkten Zugriff auf die wichtigsten Würfel (1W100 für allgemeine Proben, 1W6 für einfachen Schaden).</p><p><b>Custom Würfel:</b> Brauchst du etwas Spezielles (z.B. für Monster-Schaden oder Zufallstabellen)? Gib einfach dein gewünschtes Format ein, z.B. <code>2w8</code> oder <code>1w20+5</code>.</p><p><b>Mit Gruppe teilen:</b> Deine Würfe bleiben standardmäßig privat (nur du siehst sie im Live-Log). Willst du einen konkreten Wurf offen zeigen (z.B. eine Falle, einen Zufallseffekt), klick nach dem Würfeln auf <i>Mit Gruppe teilen</i> - dann taucht genau dieser Wurf im Team-Würfel-Feed aller verbundenen Spieler auf, klar als 'Spielleiter' markiert.</p><p><i>Hinweis: Deine Würfe tauchen sofort live im Feed auf und lösen bei Krits (1-10) oder Patzern (91-100) beim W100 auch bei dir die passenden visuellen Effekte aus!</i></p>"
,

    customSound: "<h3>🔒 Eigener privater Sound</h3><p>Hast du einen Song oder Sound, den du <b>nicht öffentlich verwenden darfst</b> (z.B. nur für den privaten Rahmen lizenziert), aber trotzdem in eurer Runde nutzen willst? Lade ihn hier hoch!</p><p>Die Datei wird <b>ausschließlich lokal in deinem Browser</b> gespeichert (nie im Repository, nie auf der öffentlich gehosteten Seite). Beim Klick auf \"Für alle abspielen\" wird sie direkt per WebRTC an die aktuell verbundenen Spieler übertragen, genau wie eure Würfe und HP-Updates auch - es findet keine Veröffentlichung auf irgendeiner Plattform statt.</p><p><i>Hinweis: Die Datei bleibt auf diesem Gerät gespeichert, bis du sie über den Papierkorb-Button wieder entfernst. Bei einem Wechsel des Browsers/Geräts musst du sie erneut hochladen.</i></p>"
,

    randomizer: "<h3>Zufallsgenerator</h3>" +
                "<p>Ein reines Prep-Werkzeug für dich als Spielleiter - nichts davon geht automatisch an die Spieler. Drei Tabellen-Pakete stehen bereit: <b>Allgemein</b> (setting-neutral), <b>Piraten</b> (generisches Flair) und <b>Eldara</b> (kanonisch, passend zum Regelpaket „eldora-arrrrr\").</p>" +
                "<p><b>NSC würfeln</b> baut in einem Rutsch einen Charakter: Name, Trefferort/Rolle, Haltung, Auffälligkeit, Motivation - optional inklusive Wesen/Monster mit einer passenden „Besonderen Eigenschaft\" aus dem Eldara-Regelwerk (rein als Flavor-Text, noch nicht an die Talentbaum-Punkte gekoppelt). Ort, Namensstil, Geschlecht, Grundhaltung und Wesen lassen sich einzeln festlegen, wenn du einen bestimmten Charakter brauchst - auf \"Zufällig\" bleibt es eine Überraschung.</p>" +
                "<p><b>Magischer Gegenstand</b> würfelt aus den 44 Eldara-Artefakten und kann per Knopf direkt <b>versteckt in die Tischmitte</b> gelegt werden - du musst nichts abtippen, nur später aufdecken.</p>" +
                "<p>Ein gewürfelter NSC lässt sich per Knopf direkt <b>in die NSC-Liste übernehmen</b> - dein dauerhaftes Gedächtnis für NPCs der Runde, siehe dazu die eigene Hilfe zur NSC-Liste.</p>" +
                "<p>Unter <b>Tabellen durchstöbern</b> findest du alle Einzeltabellen nach Paket und Kategorie sortiert - u.a. die reguläre Eldara-Waffen-Preisliste (\"Waffen des Dunklen Meeres\", S.32), Handelswaren & Vorräte (Rum, Proviant, Pulver, S.32), sämtliche herstellbaren Gegenstände (Gifte, Öle, Heiltränke, Buff-Tränke, Bomben, Technik-Gadgets, S.30) und die vollständige Liste besonderer/magischer Gegenstände (S.33-38). Jedes Ergebnis lässt sich neu würfeln oder per Klick in die <b>SL-Notizen</b> übernehmen - Ergebnisse aus den Kategorien <b>Gegenstände</b> und <b>Waffen</b> zusätzlich direkt <b>in die Tischmitte legen</b> (Waffen landen dort korrekt mit Schaden-Feld statt als Text-Beschreibung).</p>",

    gmEingriff: "<h3>🪄 SL-Eingriff</h3>" +
                "<p>Über den <i>Eingriff</i>-Knopf in der Spielerkarte greifst du direkt in den Bogen eines Spielers ein: <b>Gegenstand, Waffe oder Geld geben</b> (negativer Betrag zieht Geld ab) und <b>Status-Effekte setzen oder entfernen</b>.</p>" +
                "<p>Hat der Spieler ein <b>Wesen/Monster</b> gewählt (Eldara-Talentbaum), kannst du hier auch <b>Monsterpunkte</b> vergeben - die treiben Rang und Skillpunkte seines Wesen-Asts, statt aus eigenen Talentpunkten zu kommen.</p>" +
                "<p>Bei aktivem Eldara-Paket kannst du hier außerdem eine <b>Sonderfreigabe: Talentbaum</b> erteilen - einer der 19 NSC-/Monster-Bäume (Werwolf, Vampir, …) wird dann für genau diesen Spieler als zusätzliche Wesen-Option wählbar (Ausnahmefall laut Regelwerk „kontaktiert bitte den Spielleiter\"). Ein Klick auf ✕ nimmt die Freigabe wieder zurück.</p>" +
                "<p><b>Verdeckt:</b> Mit dem Haken erscheint beim Spieler weder ein Logbuch-Eintrag noch ein Hinweis - der Wert ist einfach da. Gedacht für Flüche, heimlich zugesteckte Gegenstände oder eine schleichende Vergiftung, die nicht mit Fanfare ankommen sollen. Ohne Haken landet der Eingriff wie jede andere Änderung im Aktions-Logbuch des Spielers, mit dem Zusatz „vom Spielleiter\".</p>" +
                "<p><i>In deinem Live-Feed steht jeder Eingriff - auch die verdeckten, damit du nachvollziehen kannst, was du wann getan hast.</i></p>",

    gruppe: "<h3>Gruppe</h3>" +
            "<p>Sobald du im Live-Sync mit deinem Spielleiter verbunden bist, siehst du hier deine <b>Mitspieler</b>: Bild, Name, Lebenspunkte und ihre aktuellen Status-Effekte. Fällt jemand auf 10 LP oder weniger, blinkt die Zeile rot.</p>" +
            "<p>Mehr ist es absichtlich nicht - Skills, Inventar und Notizen der anderen bleiben privat bzw. Sache des Spielleiters. Die Farbe kommt vom Spielleiter-Dashboard.</p>",

    teamwuerfel: "<h3>Team-Würfel</h3>" +
                 "<p>Sobald du im Live-Sync verbunden bist, siehst du hier die <b>Würfe deiner ganzen Gruppe</b> in Echtzeit - deine eigenen eingeschlossen. Kein Discord-Webhook mehr nötig, um mitzuverfolgen, was am Tisch gewürfelt wird.</p>" +
                 "<p>Es laufen nur echte Würfe rein (Würfel-Tool, Skill- und Attributproben) - allgemeine Logbuch-Einträge wie Items oder HP-Änderungen tauchen hier nicht auf, das würde nur unnötig Rauschen. Die Farbe je Spieler entspricht der im Spielleiter-Dashboard.</p>" +
                 "<p>Der <b>letzte Wurf</b> bleibt immer sichtbar, auch wenn die Liste eingeklappt ist. Über den Haken <i>Eigene Würfe mit der ganzen Gruppe teilen</i> stellst du ein, ob deine eigenen Würfe hier bei allen landen (Standard) oder nur beim Spielleiter - der sieht sie in seinem eigenen Live-Log so oder so.</p>" +
                 "<p>Über <i>Sound abspielen, wenn ein Mitspieler würfelt</i> (standardmäßig aus) bekommst du zusätzlich akustisch mit, wenn am Tisch gewürfelt wird - praktisch, wenn du gerade woanders im Tool bist. Für die eigenen Würfe gibt's keinen doppelten Sound, den hörst du ja schon direkt beim Würfeln.</p>" +
                 "<p>Über <i>Würfe als Popup anzeigen</i> (standardmäßig aus) poppt jeder Mitspieler-Wurf zusätzlich kurz oben auf dem Bildschirm auf und verschwindet nach ein paar Sekunden von selbst (oder durch Antippen) - blockiert nichts, praktisch also auch bei vielen Würfen hintereinander im Kampf.</p>" +
                 "<p><i>Reiner Live-Feed - nichts davon wird gespeichert. Wer neu beitritt, sieht nur Würfe ab dem eigenen Beitritt.</i></p>",

    tischmitte: "<h3>Tischmitte</h3>" +
                "<p>Die Tischmitte ist eine geteilte Ablage zwischen Spielleiter und Spielern - wie Beute, die in der Mitte des Tisches liegt.</p>" +
                "<p><b>Für den Spielleiter:</b> Lege Gegenstände, Waffen oder Geld ab - entweder frei eingetippt, oder per <i>Aus Regelwerk wählen</i> direkt aus den Waffen, magischen Gegenständen, herstellbaren Sachen und Handelswaren des Regelwerks (RW4.3) übernehmen, das füllt Name und Schaden/Beschreibung automatisch aus. <b>Versteckte</b> Einträge siehst nur du - so kannst du den Loot eines Abenteuers schon vor der Session vorbereiten. Findet die Gruppe die Truhe, klickst du auf <i>Aufdecken</i> (oder <i>Alle aufdecken</i>) und die Beute erscheint bei allen Spielern. Über <i>Geben an …</i> schiebst du etwas auch direkt einem bestimmten Charakter ins Inventar.</p>" +
                "<p><b>Für Spieler:</b> Sobald der Spielleiter etwas aufdeckt, klappt die Tischmitte bei dir auf UND du bekommst ein Popup mit dem neuen Fund - so verpasst niemand Beute, nur weil er gerade woanders im Tool ist. Mit <i>Nehmen</i> wandert der Gegenstand in dein Inventar (Waffen zu den Waffen, Geld in die Kasse). Greifen zwei gleichzeitig zu, bekommt nur einer den Gegenstand - der Spielleiter entscheidet. Über <i>Eigenes ablegen</i> kannst du auch etwas aus deinem Inventar in die Mitte legen, z.B. um es einem Mitspieler zu geben - bei Stapeln (3x Verbandskasten) wählst du, wie viele davon.</p>" +
                "<p><i>Die Tischmitte des Spielleiters bleibt in seinem Browser gespeichert, bis er sie leert - auch über einen Reload hinweg.</i></p>",

    modul: "<h3>Module ein-/ausblenden</h3>" +
           "<p>Reine Übersichts-Einstellung im GM-Dashboard (Button \"Module ein-/ausblenden\"): blendet ganze Werkzeug-Panels aus, wenn sie gerade nicht gebraucht werden - z.B. den Seekampf-Tracker ausblenden, solange die Gruppe an Land ist. Ändert nichts an den Daten dahinter - ein ausgeblendetes Modul läuft im Hintergrund normal weiter synchron, taucht nur in der Oberfläche nicht auf.</p>" +
           "<p>Pro Modul zwei unabhängige Haken: <b>\"Ich sehe es\"</b> blendet das Panel nur in deinem eigenen Dashboard aus, <b>\"Spieler sehen es\"</b> blendet den passenden Abschnitt bei allen Spielern aus. Beide lassen sich getrennt setzen - du kannst z.B. den Kampf-Tracker bei dir behalten, aber vor den Spielern verstecken. Rein SL-seitige Werkzeuge (NSC-Liste, Zufallsgenerator) haben nur den ersten Haken, Spieler sehen davon ohnehin nichts.</p>" +
           "<p>\"Alles wieder einblenden\" setzt alles auf den Standard (alles sichtbar) zurück. Die Einstellung bleibt in deinem Browser gespeichert, auch über einen Reload hinweg.</p>",

    soeldner: "<h3>Söldner-Pool</h3>" +
              "<p>Ergänzung zum Feld <i>\"Gehört zu\"</i> am Charakterbogen: Söldner/Mietlinge sind vollwertige Zweitcharaktere mit eigenem Talentbaum und eigenem Rasterinventar - genauso komplex wie ein normaler Charakter. Damit nicht jeder Spieler seinen Söldner selbst von Null bauen muss, kann der Spielleiter hier fertige Söldner vorbereiten und der Gruppe zur Rekrutierung anbieten.</p>" +
              "<p><b>Für den Spielleiter:</b> Baue den Söldner ganz normal als eigenen Charakter in einem zweiten Browser-Tab (Talentbaum, Inventar, alles wie gewohnt), exportiere ihn dort über <i>\"Speichern (JSON)\"</i> und lade die Datei hier hoch. Name/Beruf werden automatisch aus der Datei übernommen, lassen sich aber überschreiben. <b>Versteckte</b> Einträge siehst nur du - so kannst du mehrere Söldner vorbereiten und erst nach und nach freigeben. Rekrutiert ein Spieler einen Söldner, verschwindet er automatisch aus dem Pool (kein doppeltes Vergeben).</p>" +
              "<p><b>Für Spieler:</b> Verfügbare Söldner erscheinen in einer eigenen Liste mit Name, Beruf und Kurzbeschreibung. Mit <i>\"Rekrutieren\"</i> wird die komplette Charakterdatei automatisch heruntergeladen - öffne danach einen <b>neuen</b> Browser-Tab, lade die Datei dort über <i>\"Laden (JSON)\"</i> und tritt mit demselben Raumcode wie gewohnt bei. Ab dann spielst du zwei Charaktere gleichzeitig in zwei Tabs.</p>" +
              "<p><i>Der Söldner-Pool des Spielleiters bleibt in seinem Browser gespeichert, auch über einen Reload hinweg.</i></p>",

    inventarraster: "<h3>Rasterinventar</h3>" +
                     "<p>Bildet das Eldara-Regelwerk ab (Kapitel \"Inventar &amp; Rucksack\"): statt einer endlosen Liste hast du feste Trageflächen - <b>Gürtel</b> (5 Plätze für alles) mit zwei eigenen <b>Waffenplätzen</b> (nur für Waffen, egal welche Größe - dort kostet jede Waffe immer nur 1 Platz) und <b>Rucksack</b> (12, weniger bei schwererer Rüstung). Jeder Gegenstand belegt laut Größentabelle 1, 2 oder 3 Felder - die Größe stellst du direkt an der Karte ein.</p>" +
                     "<p><b>Rüstung:</b> sieben Ausrüstungsplätze - <b>Kopf</b> (Helm, Hut, Maske, Augenklappe), <b>Schulter/Hals</b> (Schulterpanzer, Umhang, Mantel), <b>Brust</b> (Brustpanzer, Kleidung), <b>Hände</b> (Handschuhe, Armschienen, Haken), <b>Beine</b> (Beinschutz, Hosen), <b>Füße</b> (Schuhe, Stiefel) und 3x <b>Schmuck</b> (Ringe, Amulette, Broschen, Piercings). Kein Dropdown mehr - du ziehst ein passendes Item aus Gürtel/Rucksack auf den Platz, genau wie eine Waffe an den Gürtel-Waffenplatz (dort zählt es dann auch nur 1 Feld, egal welche Größe es sonst hat). Beim Anlegen eines neuen Items legst du optional fest, zu welchem Platz es passt und wie viel Rüstungswert es gibt - eigene Zahl statt Nachschlagetabelle, das Feld erscheint an der Karte direkt unter dem Namen. Die Summe aller getragenen Werte ergibt deine Stufe (Ungepanzert 0 / Leicht 1-10 / Mittel 11-20 / Schwer 21+), die den Rucksack <b>nicht</b> mehr verkleinert (Rüstung nimmt keinen Platz weg). Dazu kommen laut Regelwerk weitere Mali auf Bewegung/Handeln/Heimlichkeit je Stufe (Leicht -1m/–/-10, Mittel -1m/-5/-15, Schwer -2m/-10/-15) - als Hinweis angezeigt, aber wie der Zusatztaschen-Malus nicht automatisch in Würfe eingerechnet.</p>" +
                     "<p><b>Herstellen:</b> Der Knopf <i>Herstellen</i> über dem Hinzufügen-Formular öffnet die Liste der herstellbaren Gifte, Öle, Heilmittel und Tränke (Regelwerk 5.1). Du wählst die Fertigkeit (z.B. Medizin oder Voodoo), die Probe läuft mit dem Malus der Tabelle; <b>bei Erfolg</b> werden die Kosten abgezogen und der Gegenstand liegt im Inventar, bei Misserfolg bleibt dein Gold erhalten. Fehlt dir das Talent oder das Geld, ist der Eintrag gesperrt bzw. abgeblendet.</p>" +
                     "<p><b>Benutzen:</b> Gegenstände, die wie in dieser Tabelle heißen (auch Funde, Käufe und Gaben vom Spielleiter), haben einen Knopf <i>Benutzen</i>. <b>Heilsalben</b> heilen sofort. <b>Tränke</b> legen einen Status mit Rundenzähler auf deinen Bogen - Zahlen wie +25 Stärke oder +10 auf alle Fertigkeiten fließen automatisch in deine Proben ein; der Zähler läuft mit dem Kampf-Tracker des Spielleiters herunter (Regenerationstrank heilt dabei 2W10 pro Runde, das Notfall-Elixier fängt einmal den Tod bei 1 LP ab). <b>Gegengift, Blutstillende Paste, Aufputschmittel</b> und das Langsame Gegengift wirken im Kampf-Tracker deines Spielleiters (Gift, Blutung, Schlaf), <b>Gifte und Brandöl</b> setzen einen Status \"Waffe präpariert\", <b>Haftöl, Frostöl, Säureöl und Schlafgas</b> melden den Wurf dem Spielleiter.</p>" +
                     "<p><b>Zusatztaschen</b> (bis zu 3 gleichzeitig) geben zusätzliche Plätze - klein +3, groß +5 - kosten dich aber -3 bzw. -5 auf Handeln, solange du sie trägst. Das musst du selbst beim Würfeln im Bonus/Malus-Feld gegenrechnen, das Tool zieht es nicht automatisch ab.</p>" +
                     "<p><b>Aus Regelwerk wählen:</b> Das Dropdown über dem Namensfeld übernimmt Items direkt aus dem Regelwerk (Waffen, magische Gegenstände, Herstellbares, Handelswaren) - Name, Schaden bzw. der passende Ausrüstungsplatz (z.B. Schuhe → Füße, Amulett → Schmuck) füllen sich automatisch. Praktisch v.a. beim Umstieg von einem Papierbogen. Freie Eingabe bleibt daneben natürlich möglich, für alles Eigene.</p>" +
                     "<p>Zum Umsortieren am kleinen Griff-Symbol <i class=\"fa-solid fa-grip-vertical\"></i> oben links an der Karte ziehen (funktioniert per Maus genauso wie am Smartphone/Tablet mit dem Finger) und auf ein anderes Feld ziehen. Ist dort schon ein 1-Feld-Gegenstand, tauschen beide automatisch die Plätze.</p>" +
                     "<p><b>Im Kampf gesperrt:</b> Aktiviert der Spielleiter den Kampf-Modus (siehe Hilfe zum Kampf-Tracker), ist das Umsortieren vorübergehend gesperrt - das Griff-Symbol wird ausgegraut, ein Hinweis erscheint oben im Panel. Gegenstände hinzufügen, entfernen oder aufs Schiff legen geht weiterhin.</p>" +
                     "<p><b>Waffen ziehen mit um:</b> Sobald Eldara aktiv ist, verschwindet das klassische Waffen-Panel - deine Waffen landen automatisch als eigene Karten im Raster (Standardgröße 2 Felder, änderbar), inklusive Schaden-Feld und Würfel-Knopf. Passt eine Waffe mangels Platz nicht rein, bleibt sie vorerst im alten Bestand und du bekommst eine Warnung. Schaltest du Eldara wieder aus, wandern alle Waffen automatisch zurück ins klassische Panel.</p>" +
                     "<p><i>Vereinfacht gegenüber dem Regelwerk: 0,5-Gegenstände (Dolche, Tränke) belegen hier volle 1 Feld statt sich zu zweit einen Platz zu teilen, und Zweihandwaffen (laut Quelle 2,5 Felder) sind wie alle anderen Waffen ab Größe 2 abgebildet - der Größenkatalog kennt aktuell nur 0,5/1/2/3.</i></p>" +
                     "<p>Diese Ansicht ersetzt die normale Inventarliste nur, solange das Regelpaket \"eldora-arrrrr\" aktiv ist - ohne Hausregel bleibt alles wie gewohnt unbegrenzt.</p>",

    runenmagie: "<h3>Schmiede-Roulette (Runenmagie)</h3>" +
                "<p>Eldara-Hausregel (RW 5.1, \"Runenmagie - Das wiedererweckte Handwerk\"): gewöhnliche Schmiede können Runen in Waffen und Rüstungen schlagen, wissen aber nicht vorher, welche Rune dabei entsteht - das entscheidet der Zufall.</p>" +
                "<p><b>Ablauf:</b> Über den Hammer-Knopf an einer Waffe oder einem Rüstungsteil legst du fest, wie viele Sockel (1-3, kostet 500/3.000/10.000 Gold) und welche Runenstärke je Sockel (Stufe 1-4, kostet 0/1.000/5.000/15.000 Gold pro Rune) du kaufen willst. Nach dem Bezahlen wird für jeden Sockel 1W6 gewürfelt: 1 Schaden/Rüstung, 2 Lebenspunkte, 3 Skill-Sockel, 4 Statuspunkte, 5 Buff-Sockel, 6 Jackpot (eigene Untertabelle, u.a. Doppelrune oder ein kostenloser Zusatzsockel).</p>" +
                "<p><b>SL-Bestätigung:</b> Das gewürfelte Ergebnis geht als Anfrage an den Spielleiter und wird erst nach dessen Bestätigung dauerhaft auf das Item angewendet - die Anfrage erscheint oben im GM-Dashboard.</p>" +
                "<p><b>Einstampfen:</b> Bist du mit einem bereits bestätigten Ergebnis unzufrieden, kannst du den Gegenstand direkt an der Karte einstampfen lassen - Gegenstand und Runen werden zerstört, du bekommst 75% des investierten Goldes zurück.</p>" +
                "<p><i>Vereinfacht: bei welchem konkreten Skill/Statuswert/Buff der Zufall zuschlägt, legt die Gruppe selbst am Tisch fest - das Tool würfelt nur die Slot-Art und Stufe.</i></p>",

    schiff: "<h3>Schiffs-Inventar</h3>" +
            "<p>Eldara-Hausregel: das Schiff als gemeinsame Heimat der Crew. Anders als die Tischmitte ist alles hier <b>immer für alle sichtbar</b> - kein Verstecken, das ist ja euer eigener Besitz.</p>" +
            "<p><b>Lager:</b> Jede Schiffsklasse hat laut Regelwerk (S.32) eine feste Kapazität - Kanonenboot 20, Schoner 50, Brigg 100, Fregatte 150, Kriegsschiff 250. Der SL wählt die Klasse; ist das Lager voll, lässt sich nichts Neues mehr ablegen.</p>" +
            "<p><b>Mitnahme-Grenze:</b> \"Nehmen\" klappt nur, wenn im eigenen <a href=\"#\" onclick=\"event.preventDefault(); showHelp('inventarraster')\">Rasterinventar</a> noch ein passendes Feld frei ist. Ist nichts frei, bekommst du eine klare Rückmeldung statt einer stillen Ablehnung.</p>" +
            "<p>Über \"Eigenes aufs Schiff legen\" gibst du umgekehrt etwas aus deinem Rasterinventar an die ganze Crew ab - ist das Lager gerade voll, bekommst du es automatisch zurück statt es zu verlieren.</p>" +
            "<p><b>Stapel und Verbrauch:</b> Gleiche Güter (Name und Größe) bilden <b>einen Stapel</b> - legst du \"Fass Nahrung\" noch einmal ab, steigt die Menge des vorhandenen Eintrags, statt dass eine zweite Zeile entsteht. Ein Stapel belegt einen Lagerplatz. Als SL zählst du bei Verbrauch die Menge mit <b>−</b> runter (oder trägst sie direkt ein); bei 0 verschwindet der Eintrag. Gilt für alle Güter - Rum, Wasser, Kanonenkugeln. Bereits vorhandene Einzelposten werden beim Laden zusammengefasst.</p>" +
            "<p><i>Das Regelwerk sagt nicht genau, wie viele Lager-Einheiten ein Gegenstand welcher Rasterinventar-Größe verbraucht - hier wird vereinfachend dieselbe Größentabelle für beides verwendet. Wirkt das Lager zu klein, einfach eine größere Schiffsklasse wählen.</i></p>" +
            "<p><i>Nur sichtbar, solange das Regelpaket \"eldora-arrrrr\" aktiv ist.</i></p>",

    kisten: "<h3>Spieler-Kisten</h3>" +
            "<p>Zusatz zum geteilten Schiffs-Inventar: jeder Spieler bekommt sein <b>eigenes, privates</b> Fach an Bord. Andere Spieler sehen den Inhalt nicht - anders als das Schiffs-Inventar, das ja bewusst für alle offen ist.</p>" +
            "<p><b>Für Spieler:</b> \"Deine Kiste\" funktioniert wie das Schiffs-Inventar - Gegenstände nehmen (landet im eigenen Rasterinventar) oder eigene Sachen aus dem Rasterinventar dort ablegen.</p>" +
            "<p><b>Für den SL:</b> Im GM-Dashboard siehst du unter \"Spieler-Kisten\" jede Kiste einzeln, kannst direkt etwas hineinlegen oder herausnehmen - praktisch um vorbereitete Belohnungen gezielt einem einzelnen Spieler zukommen zu lassen, ohne dass die ganze Crew es mitbekommt.</p>" +
            "<p><b>Stapel:</b> Gleiche Gegenstände (Name) in einer Kiste bilden ebenfalls einen Stapel und brauchen keinen neuen Platz; der SL zählt die Menge bei Verbrauch mit <b>−</b> runter.</p>" +
            "<p><b>Plätze:</b> Anders als das Lager des Schiffs (nach Gegenstandsgröße gewichtet) zählt eine Kiste schlicht die Anzahl an Gegenstands-Stapeln - ein Eintrag, egal welcher Größe oder Menge, ist ein Platz. Die Anzahl Plätze legt der SL fest (ein gemeinsamer Wert für alle Kisten).</p>" +
            "<p><i>Nur sichtbar, solange das Regelpaket \"eldora-arrrrr\" aktiv ist. Bleibt auch erhalten, wenn ein Spieler die Verbindung trennt und später wiederkommt.</i></p>",

    seekampf: "<h3>Seekampf</h3>" +
              "<p>Taktischer Kampf-Tracker für das Regelwerk-Kapitel \"Seekampf\" (Regelwerk 5.1) - Wind, Initiative, Schiffs-Werte, Manöver-Referenz, Log. Die eigentliche Karte mit den Schiffs-Token siehst und bedienst du im separaten <b>Karte</b>-Panel (eine Karte unter vielen dort, z.B. für die offene See) - Zeichnen, Kartenbild laden, Raster anpassen, Nebel des Krieges: alles dort, siehe die Hilfe zur Karte. Jedes Schiff gehört dabei genau einer Karte - es taucht nur dort auf, wo es erstellt wurde (nicht auf jeder Karte gleichzeitig). Wechselst du in ein anderes Kapitel eurer Geschichte (z.B. das Schiff legt an einer Insel an), holst du es über den Knopf <b>\"Hierher versetzen\"</b> an der Schiffskarte auf die gerade aktive Karte - seine Werte bleiben dabei erhalten.</p>" +
              "<p><b>Deine Spieler sehen live mit:</b> Sobald du ein Schiff bewegst, würfelst oder einen Effekt einträgst, aktualisiert sich die Karte bei allen verbundenen Spielern automatisch. Über die <b>Crew</b>-Chips an einem Schiff wählst du per Klick aus, welche Spieler es selbst ziehen dürfen - <b>auch mehrere gleichzeitig</b>, praktisch wenn sich die ganze Crew ein Schiff teilt. Per Klick auf die <b>Krone</b> neben einem Crew-Mitglied machst du es zum <b>Kapitän</b> - ist einer gesetzt, darf nur noch er das Schiff steuern, alle anderen bleiben nur Crew (z.B. fürs Entern), können es aber nicht mehr bewegen. Krone nochmal klicken setzt das wieder zurück auf \"jeder aus der Crew darf\". Ein Zug erscheint bei dir zunächst nur als gestrichelter <b>Vorschlag</b> im Karte-Panel unter \"Offene Zugvorschläge\"; erst \"Bestätigen\" bewegt das Schiff wirklich (oder \"Verwerfen\"). Nicht zugewiesene Schiffe (z.B. alle Gegner) bewegst weiterhin nur du.</p>" +
              "<p><b>Automatisiert</b> (reine Würfelmechanik ohne Charakterwerte): Initiative (1W10 je Schiff), Wind (1W8 Richtung, wechselt alle 1W6 Runden), Bewegung (Geschwindigkeits-Würfel des Schiffs + Windbonus, die Summe geteilt durch 3 und aufgerundet ergibt die Felder), Kanonenfeuer (W100 nach erfolgreicher Probe = Trefferquote, dazu der Schaden: 10W10 je treffender Kanone), kritische Trefferzonen (1W4) und der Rammschaden von \"Ramme voraus\". Bei <b>mehr als 300 Schaden in einer Aktion</b> weist das Log auf die fällige kritische Trefferzone hin.</p>" +
              "<p><b>Nicht automatisiert:</b> Die Manöver-Proben selbst (Steuern/Schießen/Entern/Heimlichkeit) - der Tracker kennt keine Charakterwerte, die liegen auf den einzelnen Bögen. Die Manöver-Liste unten erscheint deshalb als Nachschlage-Karte mit Malus und Effekttext; die Probe würfelt der steuernde/schießende Spieler ganz normal auf seinem Bogen (Malus manuell im Bonus/Malus-Feld eintragen). War die Probe erfolgreich, trägst du den Effekt über \"Erfolg → Effekt\" als Erinnerungs-Badge auf dem Schiff ein - prozentuale Effekte wie \"+10% Trefferchance\" fließen NICHT automatisch in die Kanonenfeuer-Trefferquote ein, du rechnest sie beim Würfeln selbst dazu (genau wie der Zusatztaschen-Malus im Rasterinventar).</p>" +
              "<p><b>Strukturpunkte:</b> Sinkt ein Schiff auf 0, markiert es der Tracker als sinkend. Kritische Trefferzonen wie \"Segel zerstört\" oder \"Mastbruch\" setzen einen dauerhaften Schadens-Badge (× zum Entfernen, sobald repariert): \"Segel zerstört\" senkt beim Bewegungswurf die Geschwindigkeit um 2 (je Segel), \"Mastbruch\" halbiert die Felder. Bei jedem Crew-Mitglied kannst du außerdem einen <b>Posten</b> wählen (Steuermann, Ausguck, Richtschütze) - das Schiff zeigt ihn als Badge, die Spieler sehen ihn mit. Den +10-Bonus würfelt der Spieler selbst auf seinem Bogen. Unter \"Spielerrollen, Kanonen-Aktionen & Felder\" findest du die Boni und die Diagonal-Regel zum Nachschlagen.</p>" +
              "<p><b>Kartenmarkierungen</b> (Riff/Insel/Wrack/Sonstiges) setzt du unten im Seekampf-Panel als eigene kleine Token - über die − / + an jedem Marker-Chip lässt sich ihre Größe auf der Karte anpassen. Sie tauchen nicht in der Einheiten-Liste oder Initiative auf und übersteht ein \"Gefecht zurücksetzen\" (nur die Kampfteilnehmer selbst werden dabei entfernt).</p>" +
              "<p><i>Vereinfacht: die Zeile mit den zusätzlichen Bewegungs-/Handeln-/Heimlichkeit-Mali je Rüstungsstufe (S.27) ist im Quelltext nicht eindeutig lesbar und daher nirgends im Tool verrechnet.</i></p>" +
              "<p><i>Nur sichtbar, solange das Regelpaket \"eldora-arrrrr\" aktiv ist. Dein Gefechtsstand bleibt wie bei Tischmitte/Schiff in deinem Browser gespeichert, auch über einen Reload hinweg.</i></p>",

    karte: "<h3>Karte</h3>" +
           "<p>Die Karte ist der allgemeine Tisch für alles außerhalb des Seekampfs: Landbewegung, Insel-Erkundung, Herumlaufen auf dem eigenen Schiff. Anders als der Seekampf-Tracker (eine feste Schiffskarte) kannst du hier beliebig viele <b>Karten</b> anlegen (\"Tortuga\", \"Schiffsdeck\", \"Dschungel-Insel\", ...) und oben im Dropdown zwischen ihnen wechseln - jede behält ihr eigenes Bild, Raster, ihre Figuren und ihren Nebel. Über <i>Bild laden</i> lädst du ein eigenes Hintergrundbild hoch, über <i>Aus Galerie wählen</i> nimmst du stattdessen einen der vorgefertigten Kartenhintergründe - die liegen schon online, Spieler laden sie beim Sync also einfach selbst per Link statt dass das komplette Bild übertragen werden muss.</p>" +
           "<p><b>Spieler-Figuren</b> entstehen automatisch, sobald jemand der Runde beitritt. Die <b>Spieler-Bewegung</b> stellst du im Karten-Panel ein: <b>Auto</b> (Standard) - die Spieler ziehen ihre Figur frei, solange kein <b>Kampf-Modus</b> läuft; im Kampf-Modus erscheint ihr Zug erst als gestrichelter <b>Vorschlag</b> unter \"Offene Zugvorschläge\", und erst \"Bestätigen\" bewegt sie wirklich. Schiffe des Seekampfs brauchen im Auto-Modus immer deine Bestätigung. Dazu gibt es <b>Immer frei</b> und <b>Immer mit Bestätigung</b>.</p>" +
           "<p><b>Token-Ringe:</b> In der Figurenliste unter der Karte hat jede Figur eine Zeile <i>Ring</i>: Farbe frei wählbar, dazu die Schnellwahl <i>Verbündet / Neutral / Feindlich / Boss / Geheim</i> (wie die Disposition in Foundry), die Breite (dünn/normal/dick) und der Stil (voll, gestrichelt, doppelt, leuchtend). Die Spieler sehen dieselben Ringe auf ihrer Karte. Bei NSC-Figuren und Spieler-Figuren merkt sich die App den Ring: wird die Figur auf einer anderen Karte neu platziert, hat sie denselben Ring.</p>" +
           "<p><b>Ringe abschalten:</b> Die Checkbox <i>Aus</i> in der Ringzeile blendet den Ring einer einzelnen Figur aus, <i>Token-Ringe</i> in den Raster-Werkzeugen schaltet alle Ringe der Karte ab. Die Einstellungen bleiben dabei erhalten.</p>" +
           "<p><b>Status und LP am Token:</b> Läuft ein Kampf im Kampf-Tracker, zeigen die Tokens darüber Symbole für Blutung, Feuer, Gift, Schlaf, Stun, Tod und Monsterform und darunter einen LP-Balken. Spieler-Figuren gehören direkt zum Teilnehmer, NSC-Figuren werden über den <b>gleichen Namen</b> im Tracker zugeordnet. Die LP von Gegnern sehen die Spieler nicht, bis du im Tracker <i>LP für Spieler sichtbar</i> einschaltest; Verbündete und Spieler-Figuren sind immer sichtbar. Mit <i>Status-Symbole</i> und <i>LP-Balken</i> in den Raster-Werkzeugen schaltest du beides für die ganze Karte ab.</p>" +
           "<p><b>Am Zug:</b> Im Kampf-Tracker schaltet <i>Nächster Zug</i> durch die Initiative-Reihenfolge (höchster Wert zuerst, nur Lebende mit Initiativewurf). Wer dran ist, bekommt auf der Karte einen goldenen Leuchtring mit Pfeil und wird den Spielern im Tracker hervorgehoben. <i>Runde weiter</i> beginnt wieder beim Ersten; mit dem Knopf <i>Zug</i> an einem Teilnehmer setzt du die Markierung von Hand.</p>" +
           "<p><b>Messen:</b> Neben der <i>Linie</i> gibt es die Messformen <i>Kreis</i> (Radius ab Mittelpunkt), <i>Kegel</i> (60° ab der Spitze) und <i>Strahl</i> (1 Feld breit) - für Flächenangriffe, Reichweiten und Sichtlinien. Ziehe mit dem Messen-Werkzeug (oder halte Umschalt/rechte Maustaste); die Form ist nur beim Ziehen sichtbar. In den Raster-Werkzeugen legst du fest, was <i>1 Feld</i> bedeutet (z.B. 200 m) und wie diagonale Schritte zählen: <i>immer 1 Feld</i> oder <i>jede 2. = 1,5</i>. Die Vorgabe <i>Seekarte</i> setzt beides nach dem Seekampf-Regelwerk (1 Feld = 200 m, zweiter diagonaler Schritt 300 m).</p>" +
           "<p><b>Pins:</b> Mit dem Werkzeug <i>Pin</i> klickst du einen Ort oder Hinweis auf die Karte (Pin ziehen = verschieben). In der Pin-Liste unter der Karte gibst du Symbol, Beschriftung und eine Notiz für die Spieler an und verknüpfst optional ein <b>Handout</b> aus der Bibliothek (goldener Rand am Pin). <i>verdeckt</i> blendet den Pin für die Spieler aus, bis du ihn aufdeckst; Pins im unaufgedeckten Nebel sehen sie ebenfalls nicht. Spieler klicken einen Pin an und lesen Beschriftung und Notiz. Das Handout bekommen sie erst, wenn du <i>Handout zeigen</i> drückst - danach öffnet der Pin es bei ihnen wieder. Dein Klick auf einen Pin öffnet dieselbe Infokarte mit dem Zeigen-Knopf. Die Pin-Liste lässt sich einklappen (die Zähler zeigen Anzahl und verdeckte Pins), nach Name, Symbol, verdeckt oder Handout sortieren und ab fünf Pins durchsuchen; das merkt sich der Browser. Die Sortierung ändert nur die Liste, nicht die Pins auf der Karte.</p>" +
           "<p><b>Auren:</b> In der Figurenliste hat jede Figur eine Zeile <i>Aura</i>. Aktiviert zeichnet sie einen Kreis mit frei wählbarem Radius (in Feldern ab dem Token-Mittelpunkt), Farbe, Darstellung (Fläche, Ring oder gestrichelt) und Bezeichnung - etwa für Buff-Reichweiten, einen Lichtkreis oder die Waffenreichweite. Spieler sehen die Aura, außer du setzt <i>nur SL</i>. Die Aura wandert mit dem Token mit und bleibt bei Kartenwechsel auf der jeweiligen Karte gespeichert; ausgeschaltet merkt sie sich ihre Einstellungen.</p>" +
           "<p><b>Mehrfachauswahl:</b> Mit dem Werkzeug <i>Auswahl</i> ziehst du einen Rahmen um mehrere Figuren oder klickst eine an; im Werkzeug <i>Zeigen</i> geht dasselbe mit gedrückter <b>Strg</b>-Taste (Strg+Klick schaltet eine Figur um, Strg+Rahmen fügt hinzu). Eine gewählte Figur zu ziehen bewegt <b>alle</b> gewählten gemeinsam - die Aufstellung bleibt erhalten und rastet als Ganzes ein. Die Leiste unter der Karte zeigt die Anzahl und bietet <i>Alle</i>, <i>Verstecken</i>, <i>Aufdecken</i> und <i>Aufheben</i>. Die Auswahl gibt es nur beim Spielleiter und wird nicht an die Spieler gesendet.</p>" +
           "<p><b>Figurenliste:</b> Die Liste <i>Spieler &amp; NSC</i> unter den Pins lässt sich wie die Pin-Liste einklappen (Zähler für Spieler, NSC und verdeckte Figuren), nach Name, Art (Spieler, NSC, Sonstige), verdeckt oder Auswahl sortieren und ab sechs Figuren nach Namen durchsuchen. Der Browser merkt sich Sortierung und Zustand; die Figuren auf der Karte bleiben unverändert.</p>" +
           "<p><b>NSCs auf die Karte:</b> In der NSC-Liste setzt der Knopf <i>Auf Karte platzieren</i> (Kartensymbol) den NSC als eigene Figur auf die gerade aktive Karte. Über das kleine Bild-Symbol links am NSC-Eintrag gibst du ihm ein eigenes Icon (statt nur einem farbigen Kreis) - das wird automatisch auf schon platzierte Token übertragen. Der Kopier-Knopf dupliziert einen NSC mit fortlaufender Nummer im Namen (\"Wache\" → \"Wache 2\" → \"Wache 3\", ...) - praktisch für eine ganze Gruppe gleicher Gegner.</p>" +
           "<p><b>Figuren ohne Kampfbeteiligung:</b> Unten in der Karte gibt es \"Markierung setzen\" - erstellt eine einfache, benannte Figur direkt auf der Karte, unabhängig von der NSC-Liste und ohne jede Verbindung zum Kampf-Tracker. Praktisch für Statisten, Deko oder alles, was die Story auf der Karte sichtbar machen soll, ohne ein vollwertiger NSC oder Kampfteilnehmer zu sein.</p>" +
           "<p><b>Nebel des Krieges:</b> Mit dem Haken \"Nebel des Krieges aktiv\" liegt die ganze Karte zunächst unter einer Decke. Mit dem Werkzeug \"Nebel aufdecken\" ziehst du einen Bereich auf - der bleibt erstmal nur für dich als Entwurf sichtbar, bis du \"Für Spieler freigeben\" klickst. \"Nebel abdecken\" macht einen bereits freigegebenen Bereich wieder unsichtbar. Eigene Spieler-Figuren tauchen für die Gruppe immer auf, egal wo im Nebel sie stehen - nur SL-eigene Figuren (NSCs, Markierungen) verschwinden im unaufgedeckten Nebel. Über das Augen-Symbol an einer Figur versteckst du sie zusätzlich komplett (Hinterhalt). Der Haken \"Markierungen in aufgedecktem Bereich ausblenden\" blendet bei dir (nicht bei den Spielern) gezeichnete Kreise/Rechtecke/Linien aus, sobald der Nebel über ihnen aufgedeckt ist - praktisch, um Planungs-Kritzeleien aufzuräumen, sobald die Spieler den Bereich ohnehin schon sehen.</p>" +
           "<p><b>Für Spieler - \"Aktualisieren\":</b> Wirkt deine eigene Karte mal hängen geblieben (z.B. nach einem kurzen Verbindungsaussetzer), holst du dir mit diesem Knopf den aktuellen Stand direkt vom Spielleiter neu - ganz ohne die Seite neu laden zu müssen.</p>" +
           "<p><b>Für Spieler - \"Raster\":</b> Blendet das vom SL eingestellte Raster nur bei dir aus (nochmal klicken zeigt es wieder). Rein lokale Anzeige-Einstellung - wirkt sich nicht auf den SL oder andere Spieler aus, bleibt aber über einen Reload hinweg erhalten.</p>" +
           "<p><b>Zeichnen/Radieren/Bild laden/Raster:</b> Eigenes Kartenbild hochladen und über Feldgröße/Versatz X/Versatz Y ans Raster anpassen, Freihand/Linie/Kreis/Rechteck zum Markieren - Farbe per Farbwähler, Deckkraft (Füllung und Umriss gemeinsam) per Regler daneben, beides wird beim Zeichnen mit der Markierung gespeichert, spätere Änderungen wirken nur auf neue Markierungen. Für jede Karte einzeln, egal ob Insel, Dschungel oder Schiffsdeck (auch die Seekampf-Karte ist einfach eine Karte hier). Die Werkzeuge sind nach Themen gruppiert: Karten, Werkzeuge, Raster, Nebel des Krieges, Spieler.</p>" +
           "<p><b>Vollbild:</b> Der Knopf \"Vollbild\" (bei dir und bei den Spielern) zeigt die Karte großformatig über allem anderen, mit einer schlanken Werkzeugleiste (Zeigen/Messen, bei dir zusätzlich Zeichnen/Radieren/Nebel/Einpassen). Esc oder \"Schließen\" bringt die Karte wieder an ihren Platz zurück - Zoom, Position und alles Gezeichnete bleiben dabei erhalten.</p>" +
           "<p><i>Nur sichtbar, solange das Regelpaket \"eldora-arrrrr\" aktiv ist. Deine Kartenbibliothek bleibt in deinem Browser gespeichert, auch über einen Reload hinweg. Der Seekampf-Tracker läuft komplett unabhängig davon weiter.</i></p>",

    kampf: "<h3>Kampf</h3>" +
           "<p>Initiative- und Zustands-Tracker für jeden Kampf, der <b>kein</b> Schiffsgefecht ist - Landkampf, Entern, eine Schlägerei in der Taverne. Positionierung/Bewegung läuft schon über das <b>Karte</b>-Panel (Spieler-Figuren gibt es dort automatisch); hier drehst du nur die Initiative-Reihenfolge und die Zustände.</p>" +
           "<p><b>Teilnehmer:</b> Verbundene Spieler holst du per Klick auf ihren Namen-Chip dazu (ihre HP bleiben auf ihrem eigenen Bogen - Schaden/Heilung, die du hier auslöst, geht als Nachricht direkt dorthin). NSCs/Gegner legst du mit Namen und HP neu an, optional den Namen aus der NSC-Liste übernehmen.</p>" +
           "<p><b>Runde weiter</b> würfelt automatisch alle tickenden Zustände aus: <b>Blutung</b> und <b>Feuermarker</b> (je 1W6 pro Marke, bis zu 5 gleichzeitig), zählt <b>Schlaf</b> herunter und weckt bei 0 auf, und löst <b>Stun</b> nach einer Runde wieder. <b>Gift</b> tickt NICHT automatisch mit - die Zähigkeits-/Immunsystem-Probe würfelt der Spieler selbst an seinem Bogen, du trägst nur \"Probe bestanden\"/\"Probe misslungen\" ein, der Rest (Schadenswürfel nach Stufe, Eskalation bei zwei Misserfolgen in Folge) läuft automatisch.</p>" +
           "<p><b>Schaden/Heilung</b> gibst du manuell mit optionalem Rüstungsbrechend-Wert (RB) und der Rüstung des Ziels ein - der Tracker rechnet RB zuerst von der Rüstung ab, erst dann vom Schaden. Ein einzelner Treffer ab 70 (Menschenform) bzw. 100 (Monsterform) Schaden wird im Log markiert - dann lohnt sich der Knopf <b>Amputation würfeln</b> (1W10-Körperteil-Tabelle, bei Spielern als dauerhafter Status auf ihrem Bogen, bei einer 10 sofortiger Tod).</p>" +
           "<p><b>0-HP-Rettungswurf:</b> Fällt jemand auf 0 HP oder weniger, würfelst du hier 1W100 - bei 1-50 kommt er sofort mit 1W10 HP zurück und schläft (1W4 Runden, Wecken oder Schaden beendet den Schlaf), bei 51-100 ist er gestorben, seine Seele hält sich noch 1W6 Runden (Rettung durch die Gruppe ist in der Zeit noch möglich).</p>" +
           "<p><b>Aktionen (RW 5.1):</b> Jede Karte hat Knöpfe für <b>Aktion A</b>, <b>Aktion B</b> und die <b>Extra-Aktion</b> - antippen = diese Runde benutzt (durchgestrichen), <i>Runde weiter</i> macht alle wieder frei. Wer 10 LP oder weniger hat, ist kampfunfähig: dann ist Aktion A gesperrt. Gestunnt oder schlafend: gar keine Aktion.</p>" +
           "<p><b>Skills zurück (RW 5.1):</b> <i>Kampf beenden (Skills zurück)</i> prüft jeden Spieler im Kampf: über 50 % LP -> seine verbrauchten Skills sind sofort wieder verfügbar, sonst muss er eine Nacht schlafen. Die <i>Nacht auswerten</i>-Funktion frischt bei Schlaf „Viel (+7 Std.)“ ebenfalls auf; bei „Wenig (6-3 Std.)“ nicht automatisch - dafür gibt es an jeder Spielerkarte den Knopf <i>Skills auffrischen</i>.</p><p><b>Nächtliche Regeneration</b> (unten im Panel) würfelt für alle Teilnehmer auf einmal je einen Würfel für Nahrung und Schlaf (viel 1W12, wenig 1W10, gar nicht 0) - ohne Grundregeneration. Ab zwei Tagen in Folge ohne Essen bzw. ohne Schlaf gibt es dafür -1W10 LP.</p>" +
           "<p><b>Kampf-Modus:</b> Der Knopf oben (<i class=\"fa-solid fa-lock-open\"></i>/<i class=\"fa-solid fa-lock\"></i>) sperrt bei allen Spielern das Umsortieren im Rasterinventar (Ziehen zwischen Feldern, Größe ändern, wenn das den Platz verschiebt) - Hinzufügen, Entfernen und Ablegen aufs Schiff bleiben davon unberührt. Beim Ein-/Ausschalten bekommt jeder Spieler kurz ein Popup mit Hinweis. Funktioniert unabhängig von Runde und Teilnehmerliste, du kannst also auch schon vor der ersten Initiative sperren (z.B. bei einem Hinterhalt).</p>" +
           "<p><i>Nur sichtbar, solange das Regelpaket \"eldora-arrrrr\" aktiv ist. \"Zurücksetzen\" löscht Runde/Initiative/Zustände, Teilnehmer und ihre HP/Amputationen bleiben erhalten - der Kampf-Modus (Inventar-Sperre) bleibt davon unberührt und muss separat ausgeschaltet werden.</i></p>",

    quests: "<h3>Quest-Logbuch</h3>" +
            "<p><b>Für den Spielleiter:</b> Lege Quests mit Name, Beschreibung und optional einer Verknüpfung zu einem NSC aus deiner NSC-Liste an. Jede neue Quest ist erst <b>versteckt</b> - nur du siehst sie. Über das Augen-Symbol teilst du sie mit der ganzen Gruppe.</p>" +
            "<p>Innerhalb einer Quest lassen sich <b>Hinweise</b> und <b>Ziele</b> einzeln hinzufügen und unabhängig von der Quest selbst freigeben - so kannst du z.B. das erste Ziel sofort zeigen und ein späteres Ziel erst enthüllen, wenn die Gruppe so weit ist. Ein Häkchen an einem Ziel markiert es für die Gruppe als erledigt (durchgestrichen).</p>" +
            "<p><b>Für Spieler:</b> Das Quest-Logbuch taucht bei dir erst auf, sobald der Spielleiter mindestens eine Quest mit der Gruppe geteilt hat - vorher siehst du nichts davon. Du siehst nur Namen, Beschreibung sowie die Hinweise und Ziele, die freigegeben wurden.</p>" +
            "<p><i>Wie die Tischmitte bleibt dein Quest-Logbuch als Spielleiter in deinem Browser gespeichert, auch über einen Reload hinweg.</i></p>",

    spielernetz: "<h3>Mein Beziehungsnetz</h3>" +
                 "<p>Deine eigene Mindmap: wer kennt wen, wer mag wen nicht. Du bist der Knoten in der Mitte, weitere NSCs trägst du per Namen ein (oder übernimmst sie mit <b>Aus Logbuch</b> automatisch aus deinem Logbuch).</p>" +
                 "<p><b>Antippen</b> eines Knotens öffnet ihn: Beziehung zu einem anderen Knoten anlegen (mit freiem Text wie <i>misstraut</i> oder <i>Bruder von</i>), bestehende löschen, Namen ändern. Zu jeder Beziehung kannst du optional einen <b>Logbuch-Eintrag als Beleg</b> verknüpfen - außerdem zeigt jeder NSC-Knoten automatisch alle Logbuch-Einträge, deren NSC-Feld genauso heißt.</p>" +
                 "<p><b>Ziehen</b> verschiebt Knoten bzw. die ganze Ansicht (am Handy mit dem Finger), die Knöpfe unten rechts zoomen, am PC geht auch Strg + Mausrad. Bleibt wie das Logbuch bei dir und wandert mit <b>Speichern (JSON)</b> mit.</p>",

    spielerlog: "<h3>Mein Logbuch</h3>" +
                "<p>Dein eigenes Tagebuch, zusätzlich zum freien <b>Notizen</b>-Feld: pro Eintrag hältst du fest, welchen <b>NSC</b> du wann getroffen hast und was er dir erzählt bzw. welche Hinweise er gegeben hat. NSC und Zeitpunkt sind optional - manchmal reicht auch einfach nur der Text.</p>" +
                "<p>Die Einträge gehören ganz dir: sie bleiben in deinem Charakterbogen, gehen nie an den Spielleiter oder andere Spieler raus, und wandern beim <b>Speichern (JSON)</b> mit deinem Charakter mit.</p>",

    netzwerk: "<h3>Beziehungsnetz</h3>" +
               "<p>Eine frei verschiebbare Mindmap für Beziehungen zwischen den <b>Helden</b> der Gruppe und deinen <b>NSCs</b> (aus der NSC-Liste) - wer hasst wen, wer schuldet wem was, wer ist mit wem verbündet.</p>" +
               "<p>Helden trägst du hier oben per Namen selbst ein - unabhängig davon, ob sie gerade online verbunden sind, bleiben sie dauerhaft als Knoten erhalten. NSCs kommen automatisch aus deiner NSC-Liste mit, Name/Löschen pflegst du weiterhin dort.</p>" +
               "<p><b>Klick</b> auf einen Knoten öffnet ihn zum Bearbeiten: neue Beziehung zu einem anderen Knoten anlegen (mit freiem Beziehungstext wie <i>misstraut</i> oder <i>Bruder von</i>), bestehende löschen, bei Helden auch Name ändern/Knoten löschen. <b>Ziehen</b> verschiebt den Knoten, <b>Mausrad</b> zoomt, auf freier Fläche <b>ziehen</b> verschiebt die ganze Ansicht.</p>" +
               "<p><i>Bleibt wie die NSC-Liste komplett lokal bei dir, geht nie an Spieler raus.</i></p>",

    nscliste: "<h3>NSC-Liste</h3>" +
               "<p>Dein Gedächtnis für Nichtspielercharaktere, die im Laufe der Runde auftauchen - bleibt komplett bei dir, geht nie an Spieler raus.</p>" +
               "<p>Über <i>In NSC-Liste übernehmen</i> beim Zufallsgenerator landet ein gewürfelter NSC mit allen Feldern (Name, Ort, Rolle, Haltung, Auffälligkeit, Motivation, Wesen) direkt hier, ohne dass du etwas abtippen musst. Du kannst NSCs aber auch von Hand eintragen - dann reicht ein Name.</p>" +
               "<p>Das freie <b>Notiz</b>-Feld pro NSC ist der Platz, um festzuhalten, wie es mit ihm weiterging - wer ihn getroffen hat, ob er noch lebt, was er der Gruppe schuldet.</p>" +
               "<p>Über die Sortierung oben rechts lässt sich die Liste nach Ort, Name oder Haltung ordnen, statt nur nach Eintragsreihenfolge.</p>" +
               "<p>Das kleine Bild-Symbol links am Eintrag gibt dem NSC ein eigenes Icon, das beim Platzieren auf der Karte statt eines farbigen Kreises erscheint - entweder als eigener Upload, oder über das <i class='fa-solid fa-images'></i>-Symbol direkt aus der mitgelieferten Token-Galerie ausgewählt (kein Hochladen nötig). Sobald ein Bild gesetzt ist, erscheint darunter ein <b>Bildausschnitt</b>-Regler - hohe Hochformat-Porträts würden sonst mittig zugeschnitten (eher Bauch als Gesicht im runden Token); mit dem Regler wählst du, ob eher der obere oder untere Teil des Bilds zu sehen ist, live in der Vorschau. Die <b>Größe</b> (in Kartenfeldern) legst du gleich hier fest. Beides wird beim Platzieren übernommen sowie auf einen schon platzierten Token nachgezogen. Der Kopier-Knopf dupliziert den NSC mit fortlaufender Nummer im Namen - praktisch für mehrere gleiche Gegner (\"Wache\" → \"Wache 2\" → \"Wache 3\", ...).</p>",

    talentbaum: "<h3>Talentbaum</h3>" +
                "<p>Der Talentbaum kommt aus dem aktiven Regelpaket. Du wählst deine <b>Hauptbäume</b> und dein <b>Wesen</b> - nur deren Skills werden angezeigt. Das Wesen bringt feste Vor- und Nachteile mit (die grünen und roten Kärtchen).</p>" +
                "<p><b>Skillpunkte (SP)</b> entstehen <i>getrennt je Baum</i>, aus dem Talentwert, der zu diesem Baum gehört (z.B. treibt dein Talent \"Nahkampf\" sowohl \"Nahkampf Klingen\" als auch \"Nahkampf Fäuste\"). Jede erreichte Schwelle (1, 10, 20 … 90, dann jeder Punkt bis 99) bringt einen SP - der zählt nur für Skills <i>dieses</i> Baums.</p>" +
                "<p><b>Rangpunkte (RP)</b> sind dagegen <i>ein gemeinsamer Topf</i> für alle Bäume: je Rangaufstieg in einem deiner drei Hauptbäume gibt es einen (max. 12). Ein RP bezahlt <b>ausschließlich</b> eine <b>Besondere Eigenschaft</b> weiter unten - Skills in einem Baum kosten nie Rangpunkte, nur Skillpunkte (auch das erste Level).</p>" +
                "<p><b>Freischaltung:</b> Rang 1 ist immer offen. Für Rang 2 in einem Baum brauchst du dort insgesamt mindestens 2 SP ausgegeben, für Rang 3 mindestens 4, für Rang 4 mindestens 6 - egal auf welche Skills des Baums verteilt (auch mehrere Rang-1-Skills weit hochgelevelt zählen). Gesperrte Skills sind ausgegraut.</p>" +
                "<p><b>Kreuz-Leveln (⚡):</b> Hast du denselben Skill-Namen in zwei deiner Bäume gelernt, zählt sein <i>effektives Level</i> als Summe beider Käufe - das siehst du am Blitz-Symbol.</p>" +
                "<p><b>Besondere Eigenschaften</b> kosten je Pick 1 Rangpunkt. Ein Rang wird erst wählbar, wenn mindestens 2 deiner Bäume diesen Rang erreicht haben und du im Rang darunter schon 2 Eigenschaften gewählt hast.</p>" +
                "<p><b>Meine Eigenschaften im Einsatz:</b> Unter den Besonderen Eigenschaften listet eine eigene Übersicht, was du gewählt hast und was es gerade bewirkt. <i>Adrenalin</i> (Heilung beim ersten Fall unter 50 % LP) und <i>Unsterblich</i> (LP auf 1/50/100 statt 0, einmal pro Tag) wirken automatisch, <i>Kämpfer</i> rechnet sich in deine Initiative ein, <i>Berserker</i> zeigt den aktuellen Schadensbonus nach deinem LP-Stand. <i>Hartnäckig</i>, <i>Kampfsanitäter</i> und <i>Meister Magus</i> haben Einsatz-Punkte zum Abhaken - sie kommen nach dem Kampf bzw. am nächsten Tag zurück, wenn dein Spielleiter „Kampf beenden“ bzw. die Nachtruhe auslöst. <i>Ledrige Haut</i>, <i>Stahlmagen</i> und <i>Unbrennbar</i> tickt dein Spielleiter im Kampf-Tracker mit.</p>" +
                "<p><b>Monsterform:</b> Hast du ein Wesen (außer Mensch) gewählt, schaltest du mit dem Knopf unter den Monsterpunkten zwischen Mensch und Monster um. Wesen/Monster-Skills lassen sich nur in Monsterform anwenden (in Menschenform erscheinen sie abgeblendet). Fällst du in Monsterform unter 25 LP, würfelt die App bei jedem Schaden einen Monster-Attributwurf gegen deinen Monsterwert: Misserfolg = du verwandelst dich zurück.</p>" +
                "<p><b>Wesen/Monster:</b> Dessen Wert steigt nicht durch eigene Talentpunkte, sondern durch <b>Monsterpunkte</b>, die dir dein Spielleiter über seinen Eingriff-Knopf vergibt (z.B. nach einem überlebten Ritual oder einem bezwungenen Monster).</p>" +
                "<p><b>Im Kampf:</b> Unter <i>Gelernte Fähigkeiten</i> hakst du benutzte Skills ab und würfelst ihren Schaden direkt (🎲). <i>Alle auffrischen</i> setzt die Haken zurück. Nach dem Regelwerk kommen Skills wieder, wenn du am Kampfende über 50 % deiner LP hast oder mindestens 6 Stunden schläfst - der Spielleiter löst das über „Kampf beenden“ bzw. die Nachtruhe aus, dann hakt sich bei dir alles von selbst ab.</p>" +
                "<p><i>Klick auf einen Skill/eine Eigenschaft = ein Level lernen, das kleine − gibt es zurück. Details siehst du, wenn du mit der Maus über der Kachel stehen bleibst.</i></p>" +
                "<p><i>Hinweis: Welcher Bogen-Talentwert genau zu welchem Hauptbaum gehört, ist eine Annahme, die die Runde mit dem Spielleiter noch bestätigen muss - kann sich also noch ändern.</i></p>",

    general: "<h3><i class='fa-solid fa-circle-info'></i> Willkommen bei EldaraHQ</h3>" +
             "<p>Dieser interaktive Charakterbogen nimmt dir die Rechenarbeit am Pen&Paper-Tisch ab und bietet ein nahtloses Multiplayer-Erlebnis - fest zugeschnitten auf die Piraten-Kampagne <b>Eldara</b> der Pen &amp; Paper-Gruppe <b>MonkeyFart</b>, mit deren Hausregelwerk „Eldara – Version Arrrrr“ (feste Talentliste, Talentbaum, Schiff, Seekampf und mehr, siehe die jeweiligen Hilfe-Texte).</p>" +
             "<h4>Top Features:</h4>" +
             "<ul>" +
             "<li><b>1-Klick-Würfeln:</b> Klicke einfach auf deine Basis- oder Skill-Werte. Krits und Patzer (10%) werden automatisch erkannt!</li>" +
             "<li><b>Multiplayer (Live-Sync):</b> Der Spielleiter (GM) generiert einen Code, Spieler treten bei. Der GM sieht alle Würfe, Lebenspunkte und Inventar-Updates sofort auf seinem Bildschirm (GM Dashboard).</li>" +
             "<li><b>Integriertes Soundboard:</b> Der GM kann live Sounds & Ambient-Tracks für alle Spieler abspielen, mixen und faden.</li>" +
             "<li><b>Drag & Drop Notizen:</b> Ziehe Einträge aus dem Logbuch oder deine gewürfelten Ergebnisse einfach mit der Maus rüber in dein Notizfeld.</li>" +
             "<li><b>Discord-Integration:</b> Verbinde einen Webhook, um alle Würfe direkt in euren Discord-Channel zu posten.</li>" +
             "<li><b>Schnellnavigation:</b> Unten bleibt eine Leiste mit Sprunglinks zu allen gerade sichtbaren Bereichen stehen (Inventar, Logbuch, Notizen, ...) - anklicken springt direkt dorthin, kein langes Scrollen nötig. Bereiche, die du gerade im Bild hast, sind hervorgehoben. Der Eintrag <i>Regelwerk</i> öffnet das Regelwerk (Basis + Anhang) als Seitenleiste zum Nachschlagen - mit Inhaltsverzeichnis und Volltextsuche; Tabellen werden auf dem Handy als Karten gezeigt. Im Talentbaum springt das Buch-Symbol an einem Skill direkt zur passenden Tabellenzeile. Auf dem Smartphone zeigt oben zusätzlich eine schmale Leiste immer deine aktuellen Lebenspunkte.</li>" +
             "<li><b>Klappbare Bereiche:</b> Fertigkeiten, Inventar, Würfel Tool, Talentbaum und die meisten anderen Panels lassen sich per Klick auf die Überschrift ein- und ausklappen - auf dem Handy starten die selten gebrauchten (z.B. Talentbaum, Karte, Seekampf) eingeklappt für mehr Überblick.</li>" +
             "</ul>" +
             "<p><i>Lokaler Speicher: Deine Eingaben werden live im Browser gespeichert. Dennoch solltest du vor/nach einer Session über 'Speichern (JSON)' ein Backup deiner Charakterdaten herunterladen!</i></p>"
};
